# Generated by Django 3.2 on 2021-08-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='custom_form',
            new_name='form',
        ),
    ]
